(source melpa)
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "pallet")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "dash")
(depends-on "elixir-mode")
(depends-on "elixir-yasnippets")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "es-lib")
(depends-on "f")
(depends-on "feature-mode")
(depends-on "handlebars-mode")
(depends-on "helm")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "peepopen")
(depends-on "popup")
(depends-on "ruby-mode")
(depends-on "rspec-mode")
(depends-on "ruby-tools")
(depends-on "rvm")
(depends-on "s")
(depends-on "textmate")
(depends-on "web-mode")
(depends-on "wrap-region")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "tree-mode") ;; needed for dirtree

;; Missing Dependencies - not found (kept locally)
(depends-on "windata") ;; needed for dirtree
(depends-on "dirtree")
